/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CriticalPathRouteImport } from './routes/critical-path'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiPublicTasksRouteImport } from './routes/api/public/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CriticalPathRoute = CriticalPathRouteImport.update({
  id: '/critical-path',
  path: '/critical-path',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTasksRoute = ApiPublicTasksRouteImport.update({
  id: '/api/public/tasks',
  path: '/api/public/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/critical-path': typeof CriticalPathRoute
  '/departments': typeof DepartmentsRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/api/public/tasks': typeof ApiPublicTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/critical-path': typeof CriticalPathRoute
  '/departments': typeof DepartmentsRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/api/public/tasks': typeof ApiPublicTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/critical-path': typeof CriticalPathRoute
  '/departments': typeof DepartmentsRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/api/public/tasks': typeof ApiPublicTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/critical-path'
    | '/departments'
    | '/roadmap'
    | '/settings'
    | '/api/public/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/critical-path'
    | '/departments'
    | '/roadmap'
    | '/settings'
    | '/api/public/tasks'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/critical-path'
    | '/departments'
    | '/roadmap'
    | '/settings'
    | '/api/public/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CriticalPathRoute: typeof CriticalPathRoute
  DepartmentsRoute: typeof DepartmentsRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicTasksRoute: typeof ApiPublicTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/critical-path': {
      id: '/critical-path'
      path: '/critical-path'
      fullPath: '/critical-path'
      preLoaderRoute: typeof CriticalPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tasks': {
      id: '/api/public/tasks'
      path: '/api/public/tasks'
      fullPath: '/api/public/tasks'
      preLoaderRoute: typeof ApiPublicTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CriticalPathRoute: CriticalPathRoute,
  DepartmentsRoute: DepartmentsRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicTasksRoute: ApiPublicTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
